"""Enterprise RBAC catalog — roles, permissions, and role→permission matrix."""

from __future__ import annotations

# Permission codes used by API Depends() and frontend
PERMISSIONS: list[tuple[str, str, str]] = [
    ("auth.login", "Login", "auth"),
    ("users.manage", "Manage users", "admin"),
    ("users.view", "View users", "admin"),
    ("roles.manage", "Manage roles", "admin"),
    ("plant.configure", "Configure plant", "admin"),
    ("audit.view", "View audit logs", "admin"),
    ("system.health", "View system health", "admin"),
    ("system.diagnostics", "API diagnostics", "admin"),
    ("heat.create", "Create heat / predict", "production"),
    ("heat.optimize", "Run optimizer", "production"),
    ("heat.whatif", "Run what-if", "production"),
    ("heat.validate", "Validate heats / actual TTT", "production"),
    ("heat.accept", "Accept/reject recommendations", "production"),
    ("heat.view_all", "View all heats", "production"),
    ("heat.view_shift", "View assigned shift heats", "production"),
    ("heat.edit_recipe", "Edit recipes", "production"),
    ("dashboard.operator", "Operator dashboard", "dashboard"),
    ("dashboard.shift", "Shift dashboard", "dashboard"),
    ("dashboard.production", "Production manager dashboard", "dashboard"),
    ("dashboard.plant", "Plant manager executive dashboard", "dashboard"),
    ("dashboard.admin", "Admin dashboard", "dashboard"),
    ("reports.view", "View reports", "reports"),
    ("reports.export", "Export reports", "reports"),
    ("reports.executive", "Executive / financial reports", "reports"),
    ("analytics.advanced", "Advanced analytics", "analytics"),
    ("research.view", "Research / SHAP / model insights", "research"),
    ("quality.view", "Quality / validation reports", "quality"),
    ("maintenance.view", "Delay / downtime / maintenance", "maintenance"),
    ("delay.manage", "Create/edit delay events", "maintenance"),
    ("alerts.view", "View alerts", "alerts"),
    ("alerts.manage", "Acknowledge alerts", "alerts"),
    ("notifications.view", "View notifications", "notifications"),
    ("enterprise.view", "Enterprise readiness pages", "enterprise"),
    ("deployment.approve", "Approve deployments", "enterprise"),
    ("ops.view", "View production operations", "operations"),
    ("ops.manage", "Manage shifts, queue, handover", "operations"),
    ("tasks.view", "View tasks", "operations"),
    ("tasks.manage", "Create and assign tasks", "operations"),
    ("mes.view", "View MES planning and boards", "mes"),
    ("mes.manage", "Manage production plans and scheduler", "mes"),
]

# Role codes matching product requirements
ROLES: list[tuple[str, str, str]] = [
    ("admin", "Admin", "Complete system control"),
    ("plant_manager", "Plant Manager", "Executive production oversight"),
    ("production_manager", "Production Manager", "Running heats and approvals"),
    ("shift_engineer", "Shift Engineer", "Assigned shift operations"),
    ("operator", "Operator", "Heat creation and recommendations"),
    ("quality_engineer", "Quality Engineer", "Accuracy and validation"),
    ("maintenance_engineer", "Maintenance Engineer", "Delays and downtime"),
    ("data_scientist", "Data Scientist", "Research and model insights"),
    ("viewer", "Viewer / Auditor", "Read-only access"),
]

# Role → permission codes
ROLE_PERMISSIONS: dict[str, list[str]] = {
    "admin": [p[0] for p in PERMISSIONS],
    "plant_manager": [
        "dashboard.plant",
        "dashboard.shift",
        "dashboard.production",
        "heat.view_all",
        "reports.view",
        "reports.export",
        "reports.executive",
        "analytics.advanced",
        "enterprise.view",
        "alerts.view",
        "notifications.view",
        "quality.view",
        "system.health",
        "audit.view",
        "ops.view",
        "ops.manage",
        "tasks.view",
        "tasks.manage",
        "mes.view",
        "mes.manage",
    ],
    "production_manager": [
        "dashboard.production",
        "dashboard.shift",
        "heat.view_all",
        "heat.accept",
        "heat.validate",
        "reports.view",
        "reports.export",
        "analytics.advanced",
        "alerts.view",
        "alerts.manage",
        "notifications.view",
        "delay.manage",
        "maintenance.view",
        "enterprise.view",
        "ops.view",
        "ops.manage",
        "tasks.view",
        "tasks.manage",
        "mes.view",
        "mes.manage",
    ],
    "shift_engineer": [
        "dashboard.shift",
        "dashboard.operator",
        "heat.view_shift",
        "heat.create",
        "heat.optimize",
        "heat.whatif",
        "heat.validate",
        "heat.accept",
        "heat.edit_recipe",
        "reports.view",
        "alerts.view",
        "notifications.view",
        "delay.manage",
        "maintenance.view",
        "ops.view",
        "ops.manage",
        "tasks.view",
        "tasks.manage",
        "mes.view",
        "mes.manage",
    ],
    "operator": [
        "dashboard.operator",
        "heat.create",
        "heat.optimize",
        "heat.whatif",
        "heat.accept",
        "heat.edit_recipe",
        "heat.view_shift",
        "heat.validate",
        "notifications.view",
        "alerts.view",
        "ops.view",
        "tasks.view",
        "mes.view",
    ],
    "quality_engineer": [
        "quality.view",
        "heat.view_all",
        "reports.view",
        "reports.export",
        "analytics.advanced",
        "research.view",
        "notifications.view",
        "alerts.view",
        "dashboard.production",
        "ops.view",
        "tasks.view",
        "mes.view",
    ],
    "maintenance_engineer": [
        "maintenance.view",
        "delay.manage",
        "heat.view_all",
        "reports.view",
        "alerts.view",
        "alerts.manage",
        "notifications.view",
        "dashboard.shift",
        "ops.view",
        "tasks.view",
        "mes.view",
    ],
    "data_scientist": [
        "research.view",
        "quality.view",
        "analytics.advanced",
        "heat.view_all",
        "reports.view",
        "enterprise.view",
        "system.health",
        "notifications.view",
        "dashboard.admin",
        "ops.view",
        "mes.view",
    ],
    "viewer": [
        "heat.view_all",
        "reports.view",
        "dashboard.plant",
        "enterprise.view",
        "quality.view",
        "alerts.view",
        "notifications.view",
        "audit.view",
        "ops.view",
        "mes.view",
    ],
}

# Map API route permission requirements (path prefix → permission)
# Used by middleware documentation; FastAPI Depends enforce per-route.
API_PERMISSION_HINTS: dict[str, str] = {
    "POST /predict": "heat.create",
    "POST /optimize": "heat.optimize",
    "POST /optimize/v2": "research.view",
    "POST /whatif": "heat.whatif",
    "POST /hybrid/evaluate": "research.view",
    "POST /validation": "heat.validate",
    "GET /heats": "heat.view_all|heat.view_shift",
    "POST /heats/export": "reports.export",
    "GET /auth/me": "auth.login",
}
